language: node_js

cache:
  directories:
    - "$HOME/.npm"

branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

install: npm ci

script:
  - npm run lint
  - npm run test
  - npm run build:web

  - VERSION=`node ./scripts/version.mjs`

  - sentry-cli releases new "$VERSION"
  - sentry-cli releases files "$VERSION" upload-sourcemaps web
  - sentry-cli releases set-commits "$VERSION" --auto
  - sentry-cli releases deploys "$VERSION" new -e "production"

deploy:
  - provider: firebase
    token:
      secure: gm6RdjfiYGq0QpXh/3Fz8zD1utc275rz54OeFipBXBbPJIXfehurjHqbHiiAAwIWy7v5jcPOwrNK2QtaWU+nS71SwlyAUvQhX2hZbmj86eR7/Ri7TB2wueO41DG/++Q615x/13Zaudg0oLUYBpCVeDFqBGi0mbjJzlMK6dZwtZI4BniucbNQdag8PN4Wjqd2o07OdyJPS+2FP3FgFG6eJ4IJboWKhPjukyQ+NmUJcXb5vwWOUoOCysdry1pnilR8u9UHr0OQp0zqavf/vsArIGYrwh+nwKv0iMMvbtIV4AzYxUX3QTnocBZN7DqiWx+vSbkpTPjiV+b6bTzPH8v9zhn0NTXPxwibEviiaDWapTR+XPJ71fplHws29ld7Y8bGwLUTh9A3OfIzds8QSDJhHGmKzJS5p9c+L8hyFCsROV63ACbYbBudOpZmt/LSwmirY/eidX19o9oEvcJGB7O3dX541DnLvYcrvPasmbdxPu6bINymiNAtHsO35SMMNIlGTAoGPvAPsFZihKpZWm69lYsdHQEPaxW8pQzqWtEQWAm2Tm8naGStw9C1rA4eXcZyD+o1yFISPO0s2tqP2MWKGNId1gUmT6TbrjbuYSqhpZN7OEETh+Lxr/gOiW8dugSqjxBf+HlL0maU7fVCAsm6eGRk/EnAclUnpOLIoYSf/LA=
    edge: true
    cleanup: false
    on:
      tags: true
